### ISSUE TITLE
https://localhost:3030 respones 404

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [slidevjs/container#1]
I had tried docker images of v0.9.1, v0.8.1, and v0.7.0, the running had been failed.

For v0.9.1(v0.8.1 is the same), it just returens 404. 
It starts fine:
```bash
docker logs lgy_node


  ●■▲
  Slidev  v0.9.1

  theme   @slidev/theme-default
  entry   /root/slides/slides.md

  slide show      > http://localhost:3030/
  presenter mode  > http://localhost:3030/presenter
  remote control  > pass --remote to enable
```
I login into the docker container and query for the web html:
```bash
docker exec -ti lgy_node /bin/sh
~/slides # wget http://localhost:3030
Connecting to localhost:3030 (127.0.0.1:3030)
wget: server returned error: HTTP/1.1 404 Not Found
```

For v0.7.0, when I started the contianer, the log is:
```bash
docker logs lgy_node


  ●■▲
  Slidev  v0.7.0

  theme   @slidev/theme-default
  entry   /root/slides/slides.md

  slide show      > http://localhost:3030/
  presenter mode  > http://localhost:3030/presenter
  remote control  > pass --remote to enable


6:19:33 AM [vite] Internal server error: The request url "/root/node_modules/@slidev/cli/node_modules/@slidev/client/main.ts" is outside of vite dev server root "/root/slides".
      For security concerns, accessing files outside of workspace root is restricted since Vite v2.3.x.
      Refer to docs https://vitejs.dev/config/#server-fsserveroot for configurations and more details.
      at ensureServingAccess (/root/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:57841:15)
      at transformRequest (/root/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:57883:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async viteTransformMiddleware (/root/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:58069:32)
```

How to fix these?

**Comment by signed-log** [comment]
Hello,
Thanks for reaching out
In the default command on the README, the out-facing port is `3000` (which is very much a typo of mine (which is now fixed)), but can easily be changed :

Docker ports declaration are in this form `-p host:container`, the `container` portion is fixed but the host portion can be set however you like

Try opening `http://localhost:3000`

**Comment by IdiosyncraticDragon** [comment]
> Hello,
> Thanks for reaching out
> In the default command on the README, the out-facing port is `3000` (which is very much a typo of mine (which is now fixed)), but can easily be changed :
> 
> Docker ports declaration are in this form `-p host:container`, the `container` portion is fixed but the host portion can be set however you like
> 
> Try opening `http://localhost:3000`

Thank you for your quick reply!
This is not my situation, I log into the docker container (docker exec -ti lgy_node /bin/sh) and find the web inside docker container is 404, and of course I get blank page outside docker through the port.

The command I had run the docker container is :
```bash
docker run --rm -d -p 10080:3030 -v /Users/llgy/test/slides/slides.md:/root/slides/slides.md --name lgy_node stig124/slidev:0.7.0
```
Then I open the web browser in the host machine and turn to the link http://localhost:10080, it failed to show the content.
And then I log into the container by :
```bash
docker exec -ti lgy_node /bin/sh
```
and try to see what the webpage it is inside the container:
```bash
~/slides # wget http://localhost:3030
Connecting to localhost:3030 (127.0.0.1:3030)
wget: server returned error: HTTP/1.1 404 Not Found
```
and it is blank.
 
The slides.md I used is 
```markdown
# Slidev

Hello, World!

---

# Page 2

Directly use code blocks for highlighting


---

# Page 3
```

I don't know how to deal with this.

**Comment by antfu** [comment]
@Stig124 Since Vite v2.3, it only listen to 127.0.0.1. Might need to pass `--remote` in the docker to expose it?

**Comment by signed-log** [comment]
> @Stig124 Since Vite v2.3, it only listen to 127.0.0.1. Might need to pass `--remote` in the docker to expose it?

This would not be the issue here, this bug seems to be docker only, and I might have an idea

**Comment by JesseEisen** [comment]
add `--remote` after `npx slidev` can slove the problem.

**Comment by IdiosyncraticDragon** [comment]
> add `--remote` after `npx slidev` can slove the problem.

It works!
Thank you very~~

**Comment by signed-log** [comment]
PR is on the way for #1 and #2
