### ISSUE TITLE
Mac OS docker directory Mapping error

### ISSUE THREAD

**Issue by JesseEisen** [slidevjs/container#2]
The command used to create a container on Mac OS will get an error.  Cause the directory `.` is invalid.  @Stig124 It is better to point out that in README.

```
$ ls  demo
slides.md
$ docker run --rm -v /full/path/of/demo:/root/slides -p 3030:3030 stig124/slidev:latest
```
Hope that can help.

**Comment by signed-log** [comment]
Hello,
Thanks for reporting that, will do
